### ISSUE TITLE
Compare Two Maps

### ISSUE THREAD

**Issue by idrissou** [acjim/AcmacsDesktop#100]
Compare two maps by generating a third map that depicts the differences, by providing a link that compares the distances in case they change.

**Comment by jidel** [comment]
@idrissou: Due to time restrictions, should we close this?

**Comment by idrissou** [comment]
@jidel : yeah makes sense.

**Comment by idrissou** [comment]
@jidel: That's the functionality I had in mind to implement after "creating a new map" to compare nodes movements, as it is related with create new map, but we decided to let it go due to time restrictions.
