### ISSUE TITLE
Make table data globaly available (per app instance)

### ISSUE THREAD

**Issue by jidel** [acjim/AcmacsDesktop#101]
As discussed in the meeting, we want to have one table per app instance (for several reasons). We therefore need a way to provide the table data globally (per app instace).

**Comment by rohankoid** [comment]
How do we handle toolbars related with maps in this case? Having multiple maps but say we want to see error lines only on one map; do we move the tool bars related with maps, into maps? @acjim/member

**Comment by jidel** [comment]
We kind of decided to only have one toolbar, that holds "global" and map specific actions.
A way to do single map actions is to check in the listening controller if the window is the currently active one.

**Comment by jidel** [comment]
Maybe sth like this:
```javascript
function change() {
    alert("a");
    var scope = angular.element($("#outer")).scope();
    scope.$apply(function(){
        scope.msg = 'Superhero';
    })
}
```

**Comment by jidel** [comment]
@rohankoid @Head: I made a little table service (https://github.com/acjim/AcmacsDesktop/tree/global_table_service) to hold the table. You can now use this service and inject it wherever you need.  
However, I don't know how the actual call to the filehandlingCtrl/api should be like. Do we need the filehandling here at all? It's basically only an api call.

**Comment by jidel** [comment]
@rohankoid: could you provide the code for the api call?

**Comment by rohankoid** [comment]
Api call for what? 

generic calls are done like this, this includes how to handle promise while making calls, please check code comment/documentation of function if you need something else (api.execute function can be currently used for 4 commands): 

``additional_params = {coordinates: list, projection: int, map: true};
api.execute(api.get_commands().NEW_PROJECTION, additional_params, output_filename_acd1).then(function(response) {                
        // do the thing
});``

for update_table there is a separate function:

`api.api.execute(additional_params, output_filename_acd1)`

which returns new output_acd1 filename as result.

**Comment by jidel** [comment]
The table data can now be gotten over 
```javascript
fileHandlingServe.getTable()
```
