### ISSUE TITLE
Nodes moved out of screen after re-optimization

### ISSUE THREAD

**Issue by rohankoid** [acjim/AcmacsDesktop#112]
![screen shot 2015-10-11 at 09 49 19 1](https://cloud.githubusercontent.com/assets/1008747/10413851/79208d5c-6ffd-11e5-9d5d-b4558d9158fa.png)

**Comment by jidel** [comment]
Is this every time the case? Or only in special cases?

**Comment by rohankoid** [comment]
Not everytime, but I'm guessing the points are kind of positioned correctly, could be problem with grid

**Comment by jidel** [comment]
The grid does not really change when the data changes. I doubt that.

**Comment by jidel** [comment]
Well, this seems to be a bug with the data, not with the map:
![screen shot 2015-10-11 at 10 20 53](https://cloud.githubusercontent.com/assets/6048968/10413940/d53c35d8-7001-11e5-93fd-c969ea07280c.jpeg)
The first line is the point before re-optimize, the second line shows the same point after re-optimize.

**Comment by jidel** [comment]
The center of the json files changes:
Center of the get_map.json
![screen shot 2015-10-11 at 10 34 18](https://cloud.githubusercontent.com/assets/6048968/10414021/a8f2f1a4-7003-11e5-9ef6-e531adef7728.jpeg)
Center of relax.json
![screen shot 2015-10-11 at 10 34 08](https://cloud.githubusercontent.com/assets/6048968/10414020/a8f06286-7003-11e5-8331-97daf24ee4ff.jpeg)

**Comment by jidel** [comment]
Is this still an issue? If yes, when does it occur?

**Comment by rohankoid** [comment]
It does, as it says when re-optimizing. But depends on what point you are moving and for test.save it is usually when the stress decreases to 296.xx

![screen shot 2015-10-29 at 23 00 13](https://cloud.githubusercontent.com/assets/1008747/10818995/63cdc382-7e91-11e5-8057-bb07ef9e8c6c.png)
![screen shot 2015-10-29 at 22 50 15](https://cloud.githubusercontent.com/assets/1008747/10818996/63d4ea22-7e91-11e5-845d-77c2b767ebf5.png)

**Comment by jidel** [comment]
Is this still an issue now?

**Comment by rohankoid** [comment]
No not any more.
