### ISSUE TITLE
Talk with Mr. Moore about final Report requirements [Daniel, Hifa]

### ISSUE THREAD

**Issue by skjallargrimmur** [acjim/AcmacsDesktop#114]
After the meeting on Monday, 12th of October we discussed with Mr. Moore that it is necessary to write a final report on the project. Hifa and me will be in charge of writing the documentation. 

Hence we will talk with Mr. Moore about the requirements for the report, especially:

- what was good / bad in the report submitted in the last term
- what to include in the final report for the ACJIM project
- any missing issues to discuss

Let me know if you have some more input regarding that discussion.

**Comment by hifakhan** [comment]
we have a little bit bt next week we will do in detail as he didnot like our last report he will check that again and discuss with us

**Comment by jidel** [comment]
Do we need to keep this open?
