### ISSUE TITLE
Manage window scope (To apply stuff only to window in focus)

### ISSUE THREAD

**Issue by krissch19** [acjim/AcmacsDesktop#116]
At the moment functions triggered by the toolbar are applied on multiple windows.
Wanted: Only apply functions to the window in focus (the one on top).

**Comment by jidel** [comment]
Two ways to do it (as I see it):
- First solution: store the the window-html and call its scope. Then either call functions directly in that scope or broadcast an event to it and listen for that event inside the window.
```javascript
function change() {
    alert("a");
    var scope = angular.element($("#outer")).scope();
    scope.$apply(function(){
        scope.msg = 'Superhero';
    })
}
```
- Second solution: broadcast event to `rootScope` and listen in the controllers for the event. Check if the current window scope is active by syncing the scope.active from window object

**Comment by Head** [comment]
could be obsolete with the task #117, please check.

**Comment by jidel** [comment]
We will still get to the point were we have several maps open.
