### ISSUE TITLE
Creating new projection

### ISSUE THREAD

**Issue by rohankoid** [acjim/AcmacsDesktop#119]
How should we handle calling the new projection.
- Should we call it (create new projection) each time a point is moved? 
- Or only after pressing the re-optimize button (as in #118)?

Scenario:
#118 wouldn't cover if the error lines #7 is visible or #71 is visible and we move the node, we have to update error lines and blobs based on moved points. 

New projection: is the process of updating acd1 files after nodes are moved on the map. @acjim/member

**Comment by jidel** [comment]
When there are error lines/ blobs, call new projection after node was moved. If there are no lines/blobs, wait for the user to click the button.

**Comment by jidel** [comment]
When point is moved a flag is set on the map scope:
```javascript
scope.pointsMoved = true;
```
Should be set to false once re-optimization is done.

**Comment by jidel** [comment]
Remove the error lines for the moved nodes
