### ISSUE TITLE
Color antigens/antisera according to JSON file

### ISSUE THREAD

**Issue by jidel** [acjim/AcmacsDesktop#12]
There is information about the color of each node on the map. Use the information provided in the JSON files to color those nodes.

There is styles sub-object in the json file. It has the following sub-objects:
- ~~drawing_order - list of lists of nodes numbers, nodes in the first sub-list must be drawn first and therefore appear behind other nodes, nodes in the last sublist are drawn last and therefore appear on top of other nodes. Nodes within a sublist are drawn in an arbitrary order.~~ see issue #13 
- points - list of styles indices for each point.
- styles - list of styles.
For each node your program need to find style number by looking in the points sublist (for node 0 take the first entry in the points list, for node 1 take the second entry, etc.) Then take the corresponding style, it contains shape, colors and other info.

Currently, the map uses test data.
In the future, this code (currently commented out) is to be used to build d3 data objects from the json data: https://github.com/acjim/AcmacsDesktop/blob/master/app/components/map/mapController.js#L16

Therefore, all the needed data should be availiable in the suboject at `d.style.shape`

**Comment by jidel** [comment]
I don't think that the color provided in the JSON is the same as Derek used in his LISP program..

**Comment by idrissou** [comment]
Professor Moor's Email on how to draw colors:

Here a quick sketch.  He calculates colors as HSV (Hue, Saturation, Value -- and not RBG or something like that).  Each dimension (H, S and V) is represented as a number between 0 and 1.  
Hue is most interesting.  It  based on the abbreviated name of the entity, e.g. the flu virus.  
For non-Dutch entities, the name is mapped directly onto the range 0-1, using the function "0-to-1-from-string" (lines 27-33).
If the name starts with a digit, it is very straightforward (0 -> 0.0, 1 -> 0.1, etc.).  
If the name starts with a letter, it is almost as straightforward (A -> 0/25; B-> 1/25; .... Z -> 24/25). 
Dutch-Names are all mapped to Orange, i.e. 0.10.  See the list of Dutch names on lines 46-55.
Saturation is based on the "Isolate", which is somehow derived from the name, using the function "smart-long-strain-abbreviation name" (see file misc.lisp, not attached), if and only if the isolate is a number .  
If it isn't a number, Saturation == 0.5. (line 66).
If it is a number, Saturation = the maximum of 0 and 1 - (log base 20 of isolate, divided by 5).  See line 64-65.
Value is first calculated using a tricky bit of logic, based on the year, but then this result is thrown away, and value is simply set to 1.0 (see line 78).  Actually, if year is a number, then use 1, otherwise use 0 (can year not be a number?).

**Comment by jidel** [comment]
https://github.com/acjim/AcmacsDesktop/pull/66

**Comment by rohankoid** [comment]
<code> else if (firstChar.toUpperCase()=="A"||firstChar=="A"){
+                h=0/25;
+            }else if (firstChar.toUpperCase()=="B"||firstChar=="B"){
+                h=2/25; <code>

is this right? just wondering since the numbering h = x/25 goes sequentially.

**Comment by jidel** [comment]
Also, the `else if (firstChar.toUpperCase() == "H" || firstChar == "H")` part seems kind of duplicate to me.

**Comment by idrissou** [comment]
The functionality is not closed, hold on your horses guys :8ball: 

@jidel: Yes it is redundant and we discussed it the last time if you remember. 
@rohankoid: yes there is a missed line. 

I confirm. I did not want to push the last version till I get the isolate from Professor Moore and push everything once for all. The functionality is not closed yet.

**Comment by jidel** [comment]
No worries. Better to check back than to have a bug in the end.

**Comment by idrissou** [comment]
True (y)

**Comment by jidel** [comment]
Update: ignore isolate values when coloring.

**Comment by jidel** [comment]
It seems like we could just use the colors provided in the JSON:
![screen shot 2015-10-20 at 18 32 27](https://cloud.githubusercontent.com/assets/6048968/10602248/94aed402-775a-11e5-82ae-847b4432580d.jpeg)

**Comment by jidel** [comment]
Waiting for response from Eugene to continue accordingly.

**Comment by jidel** [comment]
Actually, do we need feedback for this? We could just check what kind of data we get back and display it accordingly. 
If correct coloring is still necessary i.e. for concentric-circles, then we could add it later (after feedback from camebridge).
What do you think, @idrissou ?

**Comment by rohankoid** [comment]
We might really have hard time getting feedback on this, so I suggest that we process with information we have. I don't see any point in getting stuck on this anymore let's wrap this up. Regarding the data we get back, Eugene had mentioned that we should be able to check and process both type of data (for other cases but this is no different.)

**Comment by idrissou** [comment]
Makes sens and sounds good to me @jidel @rohankoid 
Worst case scenario, we still have the code to generate colors.

**Comment by jidel** [comment]
@idrissou : are you implementing it?

**Comment by idrissou** [comment]
@jidel: I think I am missing something. Wasn't it already implemented?
It was a one line code assignment thing (The one you mistyped and was always giving wrong value)

This code below:
$scope.mapData.map.styles.points.forEach(function(point, i) {

        var node_shape = "circle";
        var node_fill = "#000000";

        if (!_.isUndefined($scope.mapData.map.styles.styles[point].fill_color)) {
            node_fill = $scope.mapData.map.styles.styles[point].fill_color[0];
        }
        if (!_.isUndefined($scope.mapData.map.styles.styles[point].shape)) {
            node_shape = $scope.mapData.map.styles.styles[point].shape;
        }

        $scope.d3Data[i].style = {shape: node_shape, fill_color: node_fill};
    });

It seems someone removed it! or am I missing something?

**Comment by jidel** [comment]
I didn't write this code, so I didn't mistype it.. ;)
But anyways, we are given two possible color values by Eugene:
- A simple hex value. Thats the one that is currently implemented
- An array with a color (in hex I think?) and a opacity value. This is not implemented and is the reason why for example the `concentric_circles.acd1` displays as black nodes. However,, the Core intends to display the nodes without a color (opacity = 0)
Idk if we should implement this or just ignore this..

**Comment by idrissou** [comment]
Well, only me and you worked on this earlier, but myself I don't remember writing the code, so I thought it is you. But anyways no worries.

I seriously don't know, whatever you see fit...

**Comment by idrissou** [comment]
Now handling both cases, namely the Array one with opacity value and the string one
