### ISSUE TITLE
Consider the drawing order provided in JSON file

### ISSUE THREAD

**Issue by jidel** [acjim/AcmacsDesktop#13]
References #12 
There is a order provided in the JSON file of how the nodes are supposed to be added to the svg. This order has to be considered when adding the nodes.

There is styles sub-object in the json file. It has the following sub-objects:
- drawing_order - list of lists of nodes numbers, nodes in the first sub-list must be drawn first and therefore appear behind other nodes, nodes in the last sublist are drawn last and therefore appear on top of other nodes. Nodes within a sublist are drawn in an arbitrary order.

**Comment by idrissou** [comment]
done and pushed at  commit #1884ebd99d28747fd31de139452e9b54d630d8ee
