### ISSUE TITLE
Look into differences between JSON and acd1 files

### ISSUE THREAD

**Issue by jidel** [acjim/AcmacsDesktop#14]
According to Eugene, there is some functionality missing in `acd1` that is provided in JSON:

1. We were wondering if we could use the .acd1 file format instead of JSON to draw the maps and communicate between the front-end and the back-end.
`You may use whatever you want, if it does not damage the system. From my point of view, if you use acd1, you will have to duplicate some functionality already available in acmacs.`

What is this functionality he is talking about?

**Comment by idrissou** [comment]
There is no difference. It is the very same thing. (output acd1)
for the input acd1, it is a different story (it has no colors and it has more table data)
