### ISSUE TITLE
Clean up README.md File(s)

### ISSUE THREAD

**Issue by ProfRon** [acjim/AcmacsDesktop#140]
The README.md file(s) in trunk (and perhaps in src/core and elsewhere) are confusing:
-> Some instructions appear to be in the wrong order: Should one "grunt build" before or after "npm start"? I did it after npm start, since it seems best to build, then run -- was I wrong?  Actually, there appear to be two sections on bulding.... perhaps that's where the confusion comes from.
-> The text is fairly obviously cut-n-pasted from somewhere else, since it talks repeatedly about "your app". Particularly unsettling is the reference to "the root folder of your app", since an outsider will never be quite certain which folder is meant (trunk? trunk/src?).

**Comment by jidel** [comment]
You should not need to build the application, only if you want to distribute it. Then you need to have grunt installed:
```
npm install -g grunt
```
I updated the instructions, should be clearer now (I hope).
