### ISSUE TITLE
Draw connection lines between sera and antisera

### ISSUE THREAD

**Issue by jidel** [acjim/AcmacsDesktop#15]
How can we get the connection lines from the JSON data and draw them in d3?

**Comment by krissch19** [comment]
this is in part connected to drawing error lines. Or at least my understanding at this point is that you get both information for connection and error lines out of the error lines file. And it is handled by Eugene in the same function.

**Comment by krissch19** [comment]
Possibility to check out: When moving nodes, move endpoint of connection_line with it, instead of calling the backend for calulcating it again.
