### ISSUE TITLE
Provide a windowing functionality in HTML/JS

### ISSUE THREAD

**Issue by jidel** [acjim/AcmacsDesktop#16]
To be able to display several maps, compare and arrange them as the users likes, we need a windowing functionality using HTML/JS.
Each window should correspond to one map/file. Therefore, an seperate scope for each of those windows would be desirable.

**Comment by jidel** [comment]
I know, we don't want to use extJS, but their example is pretty neat:
http://examples.sencha.com/extjs/6.0.0/examples/classic/window/layout.html
In the navigation area, we could put our table and in the main part of the window the map.

**Comment by Head** [comment]
Still working on this... It would change the whole tab functionality I've done before. Need additional feedback before working further on it.

**Comment by jidel** [comment]
See here:
https://github.com/earmbrust/bootstrap-window/tree/master/src/js
