### ISSUE TITLE
Error on using 'Relax' or 'Error Lines' after updating table. 

### ISSUE THREAD

**Issue by rohankoid** [acjim/AcmacsDesktop#165]
After last merge either @jidel yours or mine commit has broken it I guess.

**Comment by jidel** [comment]
I think I checked.. :P

**Comment by jidel** [comment]
Works for me. At least if only one map is open. If there are more than one map (over update table), the error line calculation does not seem to work either.

**Comment by rohankoid** [comment]
ahh ok that makes sense.

**Comment by rohankoid** [comment]
``Error: 'Missing projection please run relax' ``

Since the existing projection needs to be replaced after update_table; resulting acd1 file doesn't have any projection in it, ``hint: use acd1 result from relax``

**Comment by rohankoid** [comment]
```
{
  "errors":[
    "No maps, execute relax command first"
  ]
}
```
