### ISSUE TITLE
Reoptimization as in Lispmds

### ISSUE THREAD

**Issue by rohankoid** [acjim/AcmacsDesktop#181]
Current implementation gives best map, just relax existing.

**Comment by jidel** [comment]
Something does not work as expected:
![screen shot 2015-11-12 at 08 45 56](https://cloud.githubusercontent.com/assets/6048968/11106400/9d488864-8921-11e5-81d6-e964e0425483.jpeg)

**Comment by rohankoid** [comment]
When does this happen?

**Comment by jidel** [comment]
I opened `test.save`, moved some points and tried to reoptimize.

**Comment by rohankoid** [comment]
Does this Happen every time?

**Comment by jidel** [comment]
yes, this does happen everytime to me. I'm on OS X.
Maybe I made some local changes on my system. Going to look into this.

**Comment by jidel** [comment]
Okay, was an error on my side. Got the newest core bundle and it worked.
