### ISSUE TITLE
Error Reporting unfriendly (&& core bundle broke (maybe?))

### ISSUE THREAD

**Issue by ProfRon** [acjim/AcmacsDesktop#195]
Summary: App is broken, and the error message it gives me to tell me that it is broken is less than useful.

Details: Pulled the latest updated, did an npm install && npm start, so far, so good, figured out that trunk/src/core has been moved to trunk/core, and moved the Acmacs bundle too (there's no new bundle, so I kept the old one I downloaded previously). So far so good.  App runs now.  Opens up with an example file already optimized, OK.

When I however hit the optimize button, it runs for a while, and then something breaks. I get a very cryptic error message for a little while -- text on a pinkish background, which I would have liked to have copied onto the clipboard so I could paste it here -- but it wouldn't let me.   Note I get the same error if I open a file first and then reoptimize.  Which I did (to see if it was a problem with the default map) -- and then took a screenshot (since I couldn't think of a better way to capture the error message).  

See attached file. 

Note: The files mentioned in the text are NOT on my machine, either in the directory given or elsewhere. 

![screenshot from 2015-11-15 19-05-32](https://cloud.githubusercontent.com/assets/3287003/11170225/431be87c-8bce-11e5-9bb6-c4bbcdab3735.png)

**Comment by jidel** [comment]
@ProfRon: Yes, we had to move the core bundle in order to get the build working on Linux.  
I actually experienced something similar when I moved the core bundle. I fixed it by deleting the whole project, getting it again from github, downloading the new core bundle and doing a ´´npm install´´ and ´´npm start´´.
Could you try to do this and report back here?

**Comment by jidel** [comment]
For error displaying, see #77
