### ISSUE TITLE
Bugs with newly deployed functionalities.

### ISSUE THREAD

**Issue by rohankoid** [acjim/AcmacsDesktop#212]
1. Disable map without stress: 
 * [x] After using the functionality, when we move any non-disabled points and click on reoptimize, points are moved.
2. Disable map with stress: Perhaps because of merge issues; 
  * [x] a file is being created with wrong (hardcoded) path and filename. 
  * [x] wrong/unnecessary api calls.
  * [x] After using the functionality, when we move any non-disabled points and click on reoptimize, points are still visible.
3. Create New map: 
  * [x] a file is being created with wrong (hardcoded) path and filename / *TODO*: **use save as dialog.**
  * [x] Nodes selected shouldn't be hidden in the current map from which you create a new map.
4. Coding:
  * [x] remove ``console.log`` calls
  * [x] don't communicate over ``$rootScope`` with controller, use ``$scope`` instead
5. Usability:
  * [x] Use FlashMessage instead of JS ``alert()``

**Comment by rohankoid** [comment]
**Issue found:**

After few runs of disabling nodes with and without stress and running and finally running reoptimization gives this error: 

```
{
  "errors":[
    "Traceback (most recent call last):\n  File \"/Users/rohan/Documents/workspace/AcmacsDesktop/src/../core/AcmacsCore.bundle/bin/api-acjim.py\", line 55, in main\n    output = command(chart_input=options.args[1], chart_output=options.args[3] if len(options.args) >= 4 else None, **args)\n  File \"/Users/rohan/Documents/workspace/AcmacsDesktop/src/../core/AcmacsCore.bundle/bin/api-acjim.py\", line 275, in command_relax_existing\n    p.relax(chart, rough_optimization=rough_optimization)\n  File \"/Users/rohan/Documents/workspace/AcmacsDesktop/core/AcmacsCore.bundle/acmacs/core/chart.py\", line 228, in relax\n    self.number_of_iterations = mds.run(report_intermediate_stresses)\nbackend.StdException: St13runtime_error: Stress is null: cannot continue optimization\n"
  ]
}
```

```
Stress is null: cannot continue optimization\n"
```

**Comment by idrissou** [comment]
Regarding the aforementioned error, I think you are right, sometimes I get it from the first try after cutting off too many points, leaving only 10 or so on the map.

**Comment by idrissou** [comment]
Regarding the first issue, it is due to the following lines of codes in reOptimize
![image](https://cloud.githubusercontent.com/assets/12066194/12221280/271d5c72-b794-11e5-917f-5f31fdc846e4.png)

I did work that out, assigning only the nodes to be sent to the back end, but a new error type unveils.

**Comment by idrissou** [comment]
@rohankoid , I pushed a new branch https://github.com/acjim/AcmacsDesktop/tree/DisableNodesFix

Have a look at the errors the reoptimize gives back when sending only non disabled node to it and get back to me

**Comment by rohankoid** [comment]
Temporary Fix in branch #215 is permanently fixed branch *DisableNodesFix*

**Comment by jidel** [comment]
Concerning 3.1: We could not use the saveAs dialog, just save it in a tmp folder and open a new window with that temporary file. If the user wants to keep it, he has to save it.

**Comment by rohankoid** [comment]
@jidel yes I thought about it. I was going to modify it like that

**Comment by idrissou** [comment]
@rohankoid : should we remove point 2.3 since it is more related to the newly discovered reoptimize bug?

**Comment by rohankoid** [comment]
@idrissou no, I'll just tick it off.

**Comment by rohankoid** [comment]
@idrissou 

3. Create New Map From selected Elements
   * [ ] Instead of letting user choose path and filename to save the file and reopening, save the file in temporary data path and trigger open for the saved file in a new window.  
4. Create New Map From non-selected Elements
  * [ ] Same as 3.


Steps to complete this task:

After line 448 (relax_existing call)
```javascript
var data_path = api.get_data_path();
var output_file = api.create_file_path((data_path, acd1file, ".acd1", "np");
handleFileSaveAs(output_file); // this saves the file.
```
**NOW!! appController's `handleFileOpen(filename)`** needs to be called which I don't know how to do right now from fileHandlingService

@idrissou @jidel

**Comment by jidel** [comment]
Just made a little addition. In theory you can now call this from everywhere over:
```javascript
$rootScope.$broadcast('open-file', filename);
```

**Comment by idrissou** [comment]
Good mate (y)

**Comment by idrissou** [comment]
@rohankoid :+1:

**Comment by rohankoid** [comment]
@jidel that's good, but open-file will open the whole file-dialog again (not required), it has to be handleFileOpen or add another listener which calls `handleFileOpen`

**Comment by jidel** [comment]
No, it wont. you just need to provide the filename, which will not open the file-dialog.
See here: https://github.com/acjim/AcmacsDesktop/blob/master/src/app/shared/appController.js#L34

**Comment by rohankoid** [comment]
(y) Ahh ok, commented without looking at the code

**Comment by rohankoid** [comment]
I am closing this issue, since the original issues enlisted here is solved + the thread is getting too long, and I don't want to add extra issues here. Don't want issues to get lost.
