### ISSUE TITLE
Ask to save prior to closing the application/window

### ISSUE THREAD

**Issue by jidel** [acjim/AcmacsDesktop#228]

**Comment by rohankoid** [comment]
Steps to save (not export)
1. Limit opening of only .lispmds, .save, .acd1? (having txt file opened and saving it would save it to .txt.acd1)
2. store the `original_filename` somewhere in scope.
3. on save or cmd + s (shortcut) call: ```fileHandling.handleFileSaveAs(original_filename)```
4. wait for process to complete, if completed without error display flash screen saying **''File saved!"** (or whatever you like)

**Comment by jidel** [comment]
And providing a flag that checks if any changes occured since the last save. This flag gets checked on window closing.

**Comment by rohankoid** [comment]
@jidel how can I call ``fileHanndling.getMapIsChanged()`` on close?

Procedure:

```javascript
win.on("window-close", function (windowID) {
     if(fileHanndling.getMapIsChanged()) {
        var answer = confirm ("map modified do you want to save before you exit?") //todo: use proper method
           if(answer) {
              fileHandling.handleFileSaveAs(original_filename);
              fileHanndling.setMapIsChanged(False);
              closeWindow(); //method doesn't exist yet
           } else {
            closeWindow(); //method doesn't exist yet
           }     
}
```

**Comment by jidel** [comment]
That should be called from here:
https://github.com/acjim/AcmacsDesktop/blob/master/src/app/shared/appController.js#L118
```javascript
        nwService.window.on('close', function (event) {
            // If map changed --> Ask if it should be saved
            // close action can be cancelled by:
            this.close(false);

            // ...
        });
```

**Comment by rohankoid** [comment]
someone do me a favor and add a proper dialog on this :dart:
