### ISSUE TITLE
Add current acmacs core bundle on to AcamcsDesktop git repository

### ISSUE THREAD

**Issue by rohankoid** [acjim/AcmacsDesktop#25]
Related with #8, @to_be_discussed @acjim/member 

Even though we build the core (c2r directory on home directory), we still need the acmacs file from Eugene's git repository since the api files are still located there.

**Comment by jidel** [comment]
What do you mean by the API files?

**Comment by rohankoid** [comment]
By API I mean the calls we make, for eg: ```c2env im xx xx```

the file im is inside the git repository from eugunes. This file makes call to files inside ```~/c2r/..```

So basically we need both of these, I will try to check if a copy of built made in one version of linux works on another (linux/fedora for now). If this works we might be able to write some bash scripts to make changes to path and write env variables where ever required.

**Comment by jidel** [comment]
So we would need Eugene to change this line of code:
https://github.com/acorg/acmacs/blob/3660c9b4caae32ca5b1e521f0ee1b045b872a5d6/bin/c2env#L38

**Comment by rohankoid** [comment]
Added a directory 'core' in root directory (please read readme file in the location). 
close #25

**Comment by jidel** [comment]
You could close it yourself.
