### ISSUE TITLE
Moving all nodes & displaying error lines leads to unwanted behaviour

### ISSUE THREAD

**Issue by jidel** [acjim/AcmacsDesktop#261]
1. Select all nodes
2. move them a little
3. display error lines
Result: although the nodes haven't moved in relation to themselfs, there are error lines displayed that want to put them in their original position:
![screen shot 2016-01-14 at 16 20 41](https://cloud.githubusercontent.com/assets/6048968/12328234/c700f44e-bada-11e5-86be-8c84897c5f4e.jpeg)

@krissch19: you had an idea why that was?

**Comment by krissch19** [comment]
yes I'll fix it tonight (if the issue is what I thought it was)
