### ISSUE TITLE
Bug: Fix Selected Nodes

### ISSUE THREAD

**Issue by rohankoid** [acjim/AcmacsDesktop#267]
![fix_selected_nodes](https://cloud.githubusercontent.com/assets/1008747/12361159/d0337374-bbbc-11e5-9b2c-1351a370f1a6.png)

Noticed bugs or unintended behaviours
 1. [ ] After using the feature and pressing optimize button, those fixed nodes still move they shouldn't
 2. [ ] Nodes which have been fixed shouldn't be allowed to move on screen as well. These can still be selected and moved around.
 3. [x] **Unfixing the fixed points** : Select a set of points -> fix them (unmovable) -> try to unfix them. It gives error given below.
![screen shot 2016-01-15 at 19 24 15](https://cloud.githubusercontent.com/assets/1008747/12361362/fda93784-bbbd-11e5-827d-e11826a73c49.png)
![screen shot 2016-01-15 at 19 24 23](https://cloud.githubusercontent.com/assets/1008747/12361361/fda6f104-bbbd-11e5-932b-5b8e28c8018e.png)
![screen shot 2016-01-15 at 19 24 33](https://cloud.githubusercontent.com/assets/1008747/12361363/fdaa24d2-bbbd-11e5-970a-d4727762153c.png)

On gui: those points cannot even be selected to make them re movable again.

*(note: it does work sometime)*

**Comment by idrissou** [comment]
@rohankoid : I think this issue can be closed.  Test it on your side as well and get back to me

**Comment by idrissou** [comment]
@rohankoid : please check the right boxes above. On my laptop, only the second one is still buggy.

**Comment by rohankoid** [comment]
@idrissou the first one is the one we discussed yesterday based on email from Eugene
