### ISSUE TITLE
Error lines not saved on file save

### ISSUE THREAD

**Issue by jidel** [acjim/AcmacsDesktop#276]
When displaying error or connection lines, the `is_changed` flag gets changed and the user would want to save the file with those error lines. However, on reopening of the saved files, these error lines are not shown.

Possible fixes:
- Don't change the flag when displaying error/connection lines
- Save the displayed error/connection lines with the file

@rohankoid: would the last solution be even possible?

**Comment by rohankoid** [comment]
Yeah I noticed the issue, it is kinda similar to #257

**Comment by jidel** [comment]
Well, new projection won't do us any good if we save it as `.save`, right?
As far as I know you can't save errorlines in `.save`

**Comment by rohankoid** [comment]
Rethinking this, error lines is just a click of a button, I mean it can be easily be done by user with one click, just like zoom in or zoom out. 

I am doing 
* Don't change the flag when displaying error/connection lines

second case is possible but too much work, I am ignoring it.
