### ISSUE TITLE
Additional files being created

### ISSUE THREAD

**Issue by jidel** [acjim/AcmacsDesktop#279]
Somewhere during saving some additional files are created:
![screen shot 2016-01-22 at 11 53 58](https://cloud.githubusercontent.com/assets/6048968/12508879/e73094ac-c0fe-11e5-80f3-b4673d4c1fcb.jpeg)

Delete them once they are no longer needed.
Also, it seems that sometimes the original file gets overridden and is no longer openable due to those strange file extensions.

**Comment by rohankoid** [comment]
Info: files are created on opening. I am removing myself as assignee from this.

**Comment by jidel** [comment]
More detailed issue description:
Once a file is changed and those changes saved, the original file gets extended with `.~n~`. Therefore, the file `test.save` would become `test.save.~01~`. You can't open this new file in AcmacsDesktop.

The interesing part:
Once you delete this new file `test.save.~01~` in Finder, the old file re-appears.
![screen shot 2016-01-26 at 14 05 28](https://cloud.githubusercontent.com/assets/6048968/12581292/fd2269ea-c435-11e5-994b-d8225d8edcd5.jpeg)
![screen shot 2016-01-26 at 14 06 03](https://cloud.githubusercontent.com/assets/6048968/12581294/0078ac6c-c436-11e5-9588-301153ce4ec0.jpeg)

This seems to be some OS specific backup mechanism.

**Comment by rohankoid** [comment]
Yeah I noticed those stuff as well, 
* plus it can be visible in webstorm even though not visible in finder.
