### ISSUE TITLE
Ubuntu / UNIX: Map rotation does not work

### ISSUE THREAD

**Issue by skjallargrimmur** [acjim/AcmacsDesktop#282]
On Ubuntu UNIX it is not possible to move around the map - the movement functionality doesn't work - zooming is possible though.

**Comment by jidel** [comment]
What is map rotation?

**Comment by skjallargrimmur** [comment]
Simply moving the map - in this version, the map is fixed and can't be moved anywhere

**Comment by jidel** [comment]
Thats strange? Works with v1.0.1 on ubuntu. Which files are you using?

**Comment by skjallargrimmur** [comment]
see issue #287 , problem happens with every file.

**Comment by skjallargrimmur** [comment]
Branch fix virtualbox - works when mouse integration is activated
