### ISSUE TITLE
Ubuntu/UNIX: Start Screen Disfunctional

### ISSUE THREAD

**Issue by skjallargrimmur** [acjim/AcmacsDesktop#283]
The Ubuntu/UNIX start screen does not work on the newest version - the map will not be automaticalled opened neither is possible to use any of the functions on the screen such as Open a File or Recent Project. Further, the Tag {{project.name}} appears on the screen.

![bug_start_screen](https://cloud.githubusercontent.com/assets/4130769/12530014/40a200e0-c1cf-11e5-9392-d87827cf1ea4.PNG)

**Comment by jidel** [comment]
Please get the newest version and do a `npm install` again. Should work.

**Comment by jidel** [comment]
Please confirm if this is resolved in the newest version.

**Comment by skjallargrimmur** [comment]
Does work in the newest version now - I'll close it.
