### ISSUE TITLE
Not usable menubar functions

### ISSUE THREAD

**Issue by hifakhan** [acjim/AcmacsDesktop#285]
![capture](https://cloud.githubusercontent.com/assets/12066211/12530110/a71a3186-c1d3-11e5-9210-6c6acb2b9cd2.PNG)

undo,redo, cut,copy ,paste,find,replace functions  are not working
![capture1](https://cloud.githubusercontent.com/assets/12066211/12530128/45ac02f2-c1d4-11e5-9b19-375a0b2220a6.PNG)

**Comment by rohankoid** [comment]
@hifakhan can you please write more details on how you got this issue. Also it would be nice if you could add proper titles to this issue and other issues. #284 #286
