### ISSUE TITLE
for-test.acd1

### ISSUE THREAD

**Issue by hifakhan** [acjim/AcmacsDesktop#286]
unable to open the file
![capture2](https://cloud.githubusercontent.com/assets/12066211/12530151/03041934-c1d5-11e5-86aa-ea499f669a22.PNG)

**Comment by rohankoid** [comment]
There are some issues with that specific file, out of our scope. 

Please download some new test files from https://acmacs-web.antigenic-cartography.org/ and try to open and report if this is case with more files.
