### ISSUE TITLE
Ubuntu / UNIX: Selecting Multiple Nodes not possible

### ISSUE THREAD

**Issue by skjallargrimmur** [acjim/AcmacsDesktop#287]
In the Ubuntu / UNIX 1.01 Version, it is not possible to select multiple nodes at the same time.

**Comment by rohankoid** [comment]
Is this issues same as #284 @hifakhan

**Comment by skjallargrimmur** [comment]
Okay, I closed the other issue. Any idea to resolve the problem?

**Comment by rohankoid** [comment]
@skjallargrimmur Not yet, some one with Linux will have to check this. 

@krissch19 @idrissou might be able to help with this.

Suggestion: Use the built (complete) application and provided in github instead of testing from code with npm start.

**Comment by skjallargrimmur** [comment]
@rohankoid I'm using the the built (complete) application provided from github

**Comment by jidel** [comment]
Also, working for me. Is that issue with every file you open?

**Comment by idrissou** [comment]
@skjallargrimmur: do you mean disabled nodes? If that's the case, they cannot be selected.

**Comment by rohankoid** [comment]
@idrissou, I think not, I saw the case in hifa's computer as well I think, that's the reason I wanted you guys to try testing it with built application rather than from code.

**Comment by skjallargrimmur** [comment]
This issue exists with every file that is open. . I can't a.) select nodes and b.) move the map around - it seems to me that this is some sort of OS error (I'm using 14.04 LTS), as some Hifa is having the same problem.

**Comment by skjallargrimmur** [comment]
Branch fix virtualbox - works when mouse integration is activated
