### ISSUE TITLE
Ubuntu / UNIX: "Optimize" function leads to Application Error

### ISSUE THREAD

**Issue by skjallargrimmur** [acjim/AcmacsDesktop#289]
Selecting the "optimize" function displays an Error screen in the application under Ubuntu/UNIX, as follows:

![error](https://cloud.githubusercontent.com/assets/4130769/12530507/87122ab6-c1e1-11e5-8064-44a2ea43f183.PNG)

**Comment by jidel** [comment]
and whats in the error log? Did you copy the core bundle into the right foldr?

**Comment by skjallargrimmur** [comment]
Yes, the core bundle directory (AcmacsCore.bundle/) is located in the directry of core/  

Error log is as follows:

![image](https://cloud.githubusercontent.com/assets/4130769/12537956/0a888430-c2cd-11e5-9940-3b12cfc2a988.png)

**Comment by jidel** [comment]
Okay, this seems to be a backend issue: too few titers.
@rohankoid: can we communicate this better to the user?

**Comment by rohankoid** [comment]
@skjallargrimmur Which file was this? How can I regenerate it?
@jidel there are parameters which can help with this, I want to test it first.

**Comment by skjallargrimmur** [comment]
I got this message sometimes in the built version when I click "optimize" right after starting the application.

**Comment by rohankoid** [comment]
`[86095:0209/093420:INFO:CONSOLE(74)] ""INFO Traceback (most recent call last):\n  File \"/Users/rohan/Documents/workspace/AcmacsDesktop/src/../core/AcmacsCore.bundle/bin/api-acjim.py\", line 55, in main\n    output = command(chart_input=options.args[1], chart_output=options.args[3] if len(options.args) \u003E= 4 else None, **args)\n  File \"/Users/rohan/Documents/workspace/AcmacsDesktop/src/../core/AcmacsCore.bundle/bin/api-acjim.py\", line 279, in command_relax_existing\n    p.relax(chart, rough_optimization=rough_optimization)\n  File \"/Users/rohan/Documents/workspace/AcmacsDesktop/core/AcmacsCore.bundle/acmacs/core/chart.py\", line 243, in relax\n    self.number_of_iterations = mds.run(report_intermediate_stresses)\nbackend.StdException: St13runtime_error: Stress is null: cannot continue optimization\n[acmacs-api, source: core-bundle]"", source: file:///Users/rohan/Documents/workspace/AcmacsDesktop/src/app/components/filehandling/fileHandlingService.js (74)
`
