### ISSUE TITLE
Ubuntu / UNIX: Table Screen not moveable

### ISSUE THREAD

**Issue by skjallargrimmur** [acjim/AcmacsDesktop#290]
It is not possible in Ubuntu / UNIX to drag the table screen, i.e. reducing and increasing the size of the table screen.

**Comment by jidel** [comment]
Did you toggle the table displaying?

**Comment by skjallargrimmur** [comment]
Yes, the table displaying is toggled - I toggled all displayings, but so far the map cannot be moved nor nodes can be selected.
