### ISSUE TITLE
Default JavaScript Alert Screen

### ISSUE THREAD

**Issue by skjallargrimmur** [acjim/AcmacsDesktop#291]
Alert pop up windows include the  default "JavaScript Alert" window header title . Default tags  should be removed in order to improve the usability of the application.

The Alert screen when not selecting a node:
![image](https://cloud.githubusercontent.com/assets/4130769/12530570/d17ef25e-c1e2-11e5-8a48-fa55a324c973.png)

Save Map before Exit warning:
![image](https://cloud.githubusercontent.com/assets/4130769/12530587/54464098-c1e3-11e5-94b0-bfe809aa4c2d.png)

**Comment by jidel** [comment]
Agree, for the second image: is that on the newest version??

**Comment by rohankoid** [comment]
@jidel second one should be fixed with new dialog you implemented.

@idrissou might now of first one perhaps.

**Comment by skjallargrimmur** [comment]
@jidel  It is the 1.0.1 Alpha Release version - newer versions won't work for me in Ubuntu UNIX (can't get behind the start screen in newer version)

**Comment by rohankoid** [comment]
@skjallargrimmur could you try getting latest from git and retrying`npm install`, we made some changes which might fix that issue.
