### ISSUE TITLE
Shortcut Ctrl + W closes application immediately

### ISSUE THREAD

**Issue by skjallargrimmur** [acjim/AcmacsDesktop#294]
Pressing the shortcut combination of "Ctrl + W" will close the application immediately without verifying with the user. This can cause loss of data for an user who accidently presses this combination. 

Instead, a verification screen should be added, e.g. "Do you really want to close the application without saving?" that will ask the user before quitting the application.

**Comment by jidel** [comment]
Can't reproduce this. If I change the map, I get a dialog asking me if I want to save the map. Maybe you did not modify the map?

**Comment by skjallargrimmur** [comment]
@jidel I just verified it - indeed, only if you haven't changed the map - so only minor issue. But I think the user should be asked every time if he/she really wants to close the application, even without any changes made (but it's only a minor issue, so feel free to close it)
