### ISSUE TITLE
TypeError when using error lines on simple.acd1

### ISSUE THREAD

**Issue by jidel** [acjim/AcmacsDesktop#296]
Open file `simple.acd1` and try to display error lines. The following error occurs:
![screen shot 2016-01-25 at 10 45 10](https://cloud.githubusercontent.com/assets/6048968/12547435/bfbf3866-c350-11e5-8900-4b01aa57db57.jpeg)
@idrissou: this seems to be your code
Also, please remove the `console.logs()` in the `mapCtrl`

**Comment by idrissou** [comment]
@jidel : yes and I hope it is fixed now.  Strange enough is that I don't get that error, but I understand from where it comes! I just pushed the fix
