### ISSUE TITLE
Code Variables in Error Message

### ISSUE THREAD

**Issue by skjallargrimmur** [acjim/AcmacsDesktop#302]
When a shortcut combination such as "Ctrl + P" is pressed, the error message will contain a technical field name:   {'projection'} 
![ctrlp](https://cloud.githubusercontent.com/assets/4130769/12562457/903593e2-c3a5-11e5-813f-36fe06dba747.PNG)

According to best practices, technical code variables should be omitted in error messages in order not to confuse the user.

**Comment by jidel** [comment]
What is Ctrl+P? And how did you get the error message?

**Comment by skjallargrimmur** [comment]
I was pressing several shortcuts (I guess its the shortcut for exporting files?) and I received this error message. I think you can reproduce the error when you open up the application, then run a file and optimize the nodes and after press the short cut combination for export.

**Comment by jidel** [comment]
This looks like the error I just got. Do you have the newest `AcmacsCore.bundle`?

**Comment by rohankoid** [comment]
@skjallargrimmur On error: that is from not having latest core bundle, please get latest core bundle (given that @jidel has uploaded new one for linux)
Regarding the message, that indeed is technical; should we display that message in dev mode only? The whole part > 'here is what could have gone wrong:'

**Comment by skjallargrimmur** [comment]
@rohankoid I think we should keep the messages in non-dev mode as simple as possible for security purposes. 

This bug has not appeared yet in the latest core bundle, therefore I'll close it.
