### ISSUE TITLE
Summary: Mouse behaviour in Ubuntu + Virtualbox

### ISSUE THREAD

**Issue by jidel** [acjim/AcmacsDesktop#315]
Summary issue for #282, #287, #290

nw.js seems to have a problem when running on Ubuntu in a VirtualBox VM. This is seems to be related to chromium issues since v41, as described here:
https://productforums.google.com/forum/#!topic/chrome/3Kvz9eGm87M
Current chromium version of nw.js 0.12.3
![screen shot 2016-01-30 at 15 08 48](https://cloud.githubusercontent.com/assets/6048968/12696178/bfecd39a-c763-11e5-82cd-0b48b93212b8.jpeg)

Chrome Hardware accelaration seems to be a possible problem

**Comment by jidel** [comment]
Possible fixes:
- disabling mouse integration in virtualbox
- Try chromium args:
   - `--touch-devices=123`
  - `--disable-gpu`

**Comment by jidel** [comment]
@skjallargrimmur @hifakhan:
Please try to load the branch from https://github.com/acjim/AcmacsDesktop/tree/315_virtualbox_fix and check if the issue is resolved.

**Comment by idrissou** [comment]
@jidel : I did not test it on the virtual box, but on mine it shows that nasty error of: check the image underneath.
I fixed this recently if I remember well.

![screenshot from 2016-01-31 20 12 06](https://cloud.githubusercontent.com/assets/12066194/12704250/f7cfc6c0-c856-11e5-8925-c635acbc6cab.png)

**Comment by jidel** [comment]
Okay, thats another issue, though. I only changed sth in package.json.

**Comment by jidel** [comment]
Issues seem to be fixed when mouse integration in virtualbox is disabled. This workaround becomes obsolete once a new nwjs version (`0.13.0`) and therefore a new Chromium version is used.
