### ISSUE TITLE
Error "Info ENAMETOOLONG" after reoptimization when trying to save a file - temporary local JSON file

### ISSUE THREAD

**Issue by skjallargrimmur** [acjim/AcmacsDesktop#325]
After dragging the nodes around and then clicking on the "Reoptimize" button, I receive following error message as soon as I try to save the file.
"INFO ENAMETOOLONG" and points to a local temporary JSON file.
According to the error log, there is some problem with a local variable name that causes an error in the JSON file.

UPDATE: Saving the file is not possible 

Here are screenshots of the error:
![image](https://cloud.githubusercontent.com/assets/4130769/12780283/4d8e0492-ca6d-11e5-9a46-00349906d31f.png)
![image](https://cloud.githubusercontent.com/assets/4130769/12793707/10444fac-cab2-11e5-8657-0548bd3b3b9d.png)

**Comment by jidel** [comment]
Can you please describe the steps to reproduce this error?
