### ISSUE TITLE
Nodes located out of map not selectable

### ISSUE THREAD

**Issue by skjallargrimmur** [acjim/AcmacsDesktop#327]
When I maximize the map zoom and drag the nodes out of the map (why is this even possible?), it's not possible to reset all nodes to the last position neither select all nodes at the same time for dragging without having to use the "optimize"/"reoptimize" function.

As seen on the screen below, I can't select the nodes anymore, as they are displaced out of the map:

![image](https://cloud.githubusercontent.com/assets/4130769/12782604/95bf8d12-ca7c-11e5-8b63-969fc9b82413.png)

Recommendation: Introduce a "select all nodes" function (is such a hotkey already implemented?)  and prevent the user from moving nodes out of the map.

**Comment by idrissou** [comment]
@skjallargrimmur: did it come after clicking on randomize? 
Because normally all nodes can be seen from in the main layout.

**Comment by skjallargrimmur** [comment]
@idrissou No, I purposely dragged them away from the map. 

After clicking on randomization, they are aligned in the center of the screen (in a slightly different way, of course). I was just wondering about this issue in terms of usability, in case somebody drags selected nodes to far without and wants the get it back on screen without the need of reoptimization.

**Comment by skjallargrimmur** [comment]
I just figured out a simple solution to this - just use the move function to move around the map.
