### ISSUE TITLE
Provide User Friendly Message for Innacurate Input

### ISSUE THREAD

**Issue by idrissou** [acjim/AcmacsDesktop#331]
like when selecting few seras to create a new map from an already existing map,  the backend returns "cannot create map from few serras"
we'll should prompt a user friendly message to alert the user of this case.

The message should be parsed to be displayed in a user friendly manner to the users.

**Comment by idrissou** [comment]
Hey Rohan:

1-Try the following: select 1 sera and few antigens
and create a new map
and then re-optimize:
you'll get the following error:     disconnect_having_few_titers=disconnect_having_few_titers.

2- Try the following:
1- Disconnect nodes
2- reoptimize
3- reconnect disconnected nodes:

You'll get the following error: stress is null.

**Comment by jidel** [comment]
When trying to open TAB2.txt:
![screen shot 2016-02-16 at 18 01 25](https://cloud.githubusercontent.com/assets/6048968/13083918/5e5b3762-d4d7-11e5-983c-5b3e81235ad2.jpeg)
