### ISSUE TITLE
Bug: create new map 

### ISSUE THREAD

**Issue by rohankoid** [acjim/AcmacsDesktop#332]
When creating new map from existing map, wrong serums are created in new map.

![selected](https://cloud.githubusercontent.com/assets/1008747/12896151/bd414a92-cea0-11e5-8093-1f1c11181ce8.png)

![new_map](https://cloud.githubusercontent.com/assets/1008747/12896150/bd3d2692-cea0-11e5-8f85-85c7fe0ad1a1.png)

**Comment by idrissou** [comment]
@rohankoid : strange! this does not happen on mine for the same selection.
Will investigate this after my exam.

**Comment by idrissou** [comment]
@rohankoid: It is official now. The bug is from the backend. Not from our side!
