### ISSUE TITLE
New Map functionality not working as expected

### ISSUE THREAD

**Issue by jidel** [acjim/AcmacsDesktop#377]
The create new map functionality does not seem to work as expected and always presents the selected nodes positions as they were in the original file (acd1).

**How to reproduce:**
1. Move position of some nodes
![screen shot 2016-02-18 at 14 34 56](https://cloud.githubusercontent.com/assets/6048968/13144793/f57aba52-d64c-11e5-95ee-2eb69dbbdb0b.jpeg)
![screen shot 2016-02-18 at 14 35 03](https://cloud.githubusercontent.com/assets/6048968/13144794/f57ad000-d64c-11e5-829b-a85e3288a721.jpeg)
2. Select all of them and click on new map
![screen shot 2016-02-18 at 14 35 39](https://cloud.githubusercontent.com/assets/6048968/13144796/f57e93ca-d64c-11e5-804d-eaa6d681659c.jpeg)
3. The result in the new map:
![screen shot 2016-02-18 at 14 35 50](https://cloud.githubusercontent.com/assets/6048968/13144795/f57dd796-d64c-11e5-9460-7a11cfb9586b.jpeg)
The nodes seem to move to the position they had in the original acd1

**Comment by idrissou** [comment]
@jidel : It is not a bug. It is the normal behavior.
That's why Derek used the compare two maps functionality after creating a new map in the demo, with arrows pointing to where nodes moved.

You can ask Derek in an email and he'll confirm that.

**Comment by jidel** [comment]
I'm not sure I can follow. Either I am not understanding you or you are not understanding my problem.

My problem lies with the pictures 2 and 3 (Look at the green box and where it moves). I am selecting the nodes in step 2 and create a new map. However, the resultign new map features not the positon of the nodes as I selected them (as you can see at the green box). Are you sure that is intended behaviour? What would the use case be for that? I would assume that the newly created map is just as the nodes I selected to create it.

**Comment by jidel** [comment]
I'm not sure I can follow. Either I am not understanding you or you are not understanding my problem.

My problem lies with the pictures 2 and 3 (Look at the green box and where it moves). I am selecting the nodes in step 2 and create a new map. However, the resultign new map features not the positon of the nodes as I selected them (as you can see at the green box). Are you sure that is intended behaviour? What would the use case be for that? I would assume that the newly created map is just as the nodes I selected to create it.
@idrissou

**Comment by idrissou** [comment]
hey @jidel : create a new map is not a copy paste of the map. It is intended to show a slight change in the behavior of nodes. That's how I understood it.
When Derek came over, that's what happened and he used afterwards the compare to track which direction nodes moved. To me it is the intended behavior. Even in the early stage with vis.js, I developed it that way with a compare to track the movement.
You could always ask Derek or Eugine for this.
