### ISSUE TITLE
Change size of html-window accoring to nw.js window

### ISSUE THREAD

**Issue by jidel** [acjim/AcmacsDesktop#41]
When resizing the nw.js window, the html-windows should shrink if they would be outside the visible area. A maximized html-window should move with the nw-js window and should always fill the whole area.

**Comment by Head** [comment]
I opend up an issue on the ngwindows project. Let's give him some time:
https://github.com/sinmsinm/angular-window-manager/issues/1

**Comment by jidel** [comment]
That is more of a missing feature of the original project (http://www.rlamana.es/ventus/code/examples/simple/#) than a bug.
I think we have to handle this ourselfs.

**Comment by jidel** [comment]
Closed via #87
