### ISSUE TITLE
handling backend output file formats

### ISSUE THREAD

**Issue by krissch19** [acjim/AcmacsDesktop#42]
the filehandler of the application is not yet able to read the .json files we get as output, or am I wrong? 

When I try opening the "data_errorlines.json" or "concentric_circle.json" it doesn't display anything. Yet those are the formats we get back as output from the backend.
This will be required for map drawing cause the style-information and the errorlines and stuff is in those formats. Not in the input formats that are currently handled.

**Comment by jidel** [comment]
No, currently only `acd1` files are handled. Once we have Eugenes new file format, we can change this accordingly. However, the layout object and error lines should stay the same.

**Comment by krissch19** [comment]
I doubt he will change the output file format? And as long as we're not able to read this I can't implement anything ("translation thing", style stuff, error lines, correction lines), cause all the information is in there. Sure I can do it separately, without implementing it directly but I thought that's what we wanted to avoid.

**Comment by jidel** [comment]
Of course, he is planning on providing us with a special json based file format that holds tables and map data. The actual layout of the map data should not change, though.
For your problem you can  just put a sample `acd1` file with error lines as static code in the filehandling controller: https://github.com/acjim/AcmacsDesktop/blob/master/app/components/filehandling/filehandlingController.js

**Comment by idrissou** [comment]
Hello guys, the content of the acd1 and json files that we got from the
backend is exactly the same thing. It is just the format that is different.

so I guess it shouldn't be a problem here.



2015-08-27 11:27 GMT+10:00 Johannes <notifications@github.com>:

**Comment by krissch19** [comment]
So we cleared it this morning in prac, but just wanted to clarify for everyone that what was meant in this issue is backend-output("json") versus the backend-input("acd1") format.
And I guess I'll do it as you suggest Johannes. Just not sure if I'm able to get it all done before I leave for the weekend tomorrow morning.
