### ISSUE TITLE
Add new AcmacsCore output file to project

### ISSUE THREAD

**Issue by jidel** [acjim/AcmacsDesktop#43]
Eu provided us with a new json format for communication between the front and the back end. Add this json file to the project folder `/test/data`

**Comment by jidel** [comment]
@rohankoid: can this be closed then? https://github.com/acjim/AcmacsDesktop/commit/aa5e35b18b1996e1a95ee3c7462ee93449f930c6
What about the npm-debug.log. Is that needed?

**Comment by rohankoid** [comment]
In directory: test/data/

For table data please focus on get_table_concentric.json and for map drawing get_map.json other files are not relevant for you right now I guess.
