### ISSUE TITLE
Change filehandling to handle new json files

### ISSUE THREAD

**Issue by jidel** [acjim/AcmacsDesktop#44]
As described in #43, there is a new `json` file format that is to be used instead of `acd1`.
This is going to be the new way of communication with the backend. Therefore, remove the ability to open `acd1` files in our application and change filehandling to support this new `json` format.

Waits for #43

**Comment by rohankoid** [comment]
Unlike before where we were handling '.json' and '.acd1' files only, now our project should be able to handle multiple file types, '.txt, .acd1, .bz2, .csv, .xls, .save, .sav' and few more but not '.json' (there seems to be no support for this yet. @Head @jidel 

Even though you can accept these files, these files will be further sent to EU's api to get .json files for now to start on development you can take these files (in test/data/) and parse them; for table data please focus on get_table_concentric.json and for map drawing get_map.json

**Comment by Head** [comment]
should work now. Let's test when @rohankoid finished the work on the api
