### ISSUE TITLE
Creating a functionality to descale data back to its original form and save it in a json-like file

### ISSUE THREAD

**Issue by idrissou** [acjim/AcmacsDesktop#49]
For the time being, two solutions arise on hand when it comes to how we should display our data.

The first is to keep data in its original form (without scaling) and to zoom on it. The only bottleneck to this option is the huge amount of grid layers that will be created in our svg.

The second option is to scale data, only to discale if the users wants to save it on his hard-drive.

The purpose of this test is to make sure that JavaScript handles well the descaling with very small numbers (ex -0.7499849844) so that we go for the scaling option as it is the most sound one.

**Comment by idrissou** [comment]
Hey Guys, 

The invert scale functionality seems to work fine, but not that quite precise (check the last digit in the second example)

What do you think? 

![Uploading image.png…]()![example](https://cloud.githubusercontent.com/assets/12066194/9698089/f4041946-53ea-11e5-8f37-069a272e956f.png)

**Comment by jidel** [comment]
If it is only the last digit, that sound pretty accurate to me.
Btw: you can mention us all by typing `@acjim/owners @acjim/member`. No need to assign everybody.

**Comment by rohankoid** [comment]
Looks pretty accurate, should be more than fine if we have up to 12 decimal points right.

**Comment by idrissou** [comment]
Sounds Good (y)

**Comment by jidel** [comment]
Can this be closed then?

**Comment by idrissou** [comment]
yes
