### ISSUE TITLE
Handling Temporary files

### ISSUE THREAD

**Issue by rohankoid** [acjim/AcmacsDesktop#59]
Would we @acjim/member  need package like this to handle temporary files? It does offer quite a few steps to handle it

https://www.npmjs.com/package/temp

**Comment by jidel** [comment]
Also have a look at these:
https://github.com/nwjs/nw.js/wiki/App#datapath
https://github.com/nwjs/nw.js/wiki/Save-persistent-data-in-app
http://www.mikeball.info/blog/chromium-data-path/

**Comment by jidel** [comment]
I think we kind of have to look into that. As I package the application, I run into the following error:
![screen shot 2015-10-19 at 19 52 06](https://cloud.githubusercontent.com/assets/6048968/10574676/f9b11ede-769a-11e5-8097-26a190092c43.jpeg)
Seems like this is related to nw.js not being able to place temporary files into a compressed application (what a `.nw` file basically is).

**Comment by jidel** [comment]
**Problem:** If there are more than one app instances, they share the same "data store". Closing one window deletes all files which leads to errors.

**Suggestion:** Use a folder (some hash value as the name) for each app instance. Then, delete the corresponding folder if the instance is closed.

**Comment by jidel** [comment]
It seems the files are deleted, but not the folder.

**Comment by rohankoid** [comment]
yeah I knew of it, was just too lazy to delete them, and came with a theory that creating directory requires more resources and let it be. Solution would be to add
`fs.rmdirSync(dirPath);` after line no.`82` on appController.js

Or I'll commit this with other changes, on another branch may be.
