### ISSUE TITLE
Problem with file handling

### ISSUE THREAD

**Issue by rohankoid** [acjim/AcmacsDesktop#60]
Issue with filehandling, especially if the file has been created  and trying to access on the same single request. 

Would it be an option to store our files into /tmp/ folder?

**Comment by jidel** [comment]
Are you talking about the current version?

**Comment by rohankoid** [comment]
Yes! Checking if the file exists returns result randomly. I am trying to figure out the behaviour currently.

**Comment by jidel** [comment]
What kind of error? Provide some information.
However, the functionality (especially new file) is not implemented, we probably have to talk about our desired behaviour.

**Comment by rohankoid** [comment]
This issue is not up for discussion yet, this topic was rather for personal reminder. We could still discuss more on this tomorrow.

**Comment by rohankoid** [comment]
it would be wise for every one to give a try to make api/script calls synchronous in node.js @acjim/member
