### ISSUE TITLE
Pushing Clipped Elements From the Edge of the SVG

### ISSUE THREAD

**Issue by idrissou** [acjim/AcmacsDesktop#62]
As the image underneath shows, some of the nodes are clipped from the edge of the SVG, and we only see half of them.

To address this, we’ll incorporate a padding number when setting the range of the scales. This will help push our elements in, away from the edges of the SVG, by the specified padding number to prevent them from being clipped.

![padding](https://cloud.githubusercontent.com/assets/12066194/9924844/e0667504-5d46-11e5-9d67-2e57eade944f.png)

**Comment by idrissou** [comment]
closed. Now looks like this. https://github.com/acjim/AcmacsDesktop/commit/3a96dfb55d59001e9f12b46b6c34462e10afbd77

![padding](https://cloud.githubusercontent.com/assets/12066194/9924946/fea1ea16-5d47-11e5-94e9-ed004de82633.png)

**Comment by jidel** [comment]
:+1:  nice.

**Comment by idrissou** [comment]
Thanks. We could change that to percentages if you want.It is a one line of code after all. 
But since the height and the width are static now, it is better to keep the padding static too.

**Comment by jidel** [comment]
True. Let's just keep that in mind for later.
