### ISSUE TITLE
getting vagrant and the core running in windows

### ISSUE THREAD

**Issue by Head** [acjim/AcmacsDesktop#67]
Trying to setup the backend in a virtual box.

**Comment by Head** [comment]
vagrant@packer-virtualbox-iso-1422601639:/vagrant$ ./core/AcmacsCore.bundle/bin/c2env api-acjim.py ./data/tmp/input_1442983556191.json ./test/data/simple2.acd1 ./test/data/input_simple12334.json ./test/data/input_simple12334.acd1
Python 3.4.0 (default, Jun 19 2015, 14:24:19) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by jidel** [comment]
Call works in Ubuntu.

**Comment by rohankoid** [comment]
++ tested on mine too.

**Comment by jidel** [comment]
@rohankoid: did you try to run it on a vanilla ubuntu? I run into the following error:
`python3: error while loading shared libraries: libpython3.4m.so.1.0: cannot open shared object file: No such file or directory`
I don't think thats supposed to happen, right?

**Comment by jidel** [comment]
`AcmacsCore.bundle` should now work on a fresh Ubuntu 14.04 LTS x64 version.
