### ISSUE TITLE
Draw error lines in d3 from real data

### ISSUE THREAD

**Issue by jidel** [acjim/AcmacsDesktop#7]
Add the possibility to draw error lines in d3 from the real backend JSON data.

1. The error lines should have special color codes (blue for too far away, red for too close). Does acmacs provide this information? If yes, how do we get this information?
`This information is not provided, your program has to figure it out itself.`

2. Information on the data structure: That is how acmacs handles the error lines:
https://github.com/acorg/acmacs/blob/f52efee01c143d1fdba169595e8a6588e1f2ea2e/acmacs-web/yui/acmacs/js/acmacs-connections-svg.js#L53

**Comment by krissch19** [comment]
To integrate it within application it needs to be adapted to work with json-objects. So I propose implementing the translator first (assigned myself to that issue just now). Then I would integrate it to the application.

**Comment by rohankoid** [comment]
@krissch19 #68 please check if this file relates with this issue.

**Comment by jidel** [comment]
What's the status about this?

**Comment by krissch19** [comment]
working on it

**Comment by rohankoid** [comment]
talk with Eugene on how error lines can be updated without relaxing the map.

**Comment by rohankoid** [comment]
TODO: error lines should be synchronous with the map (relax or on points moved)

**Comment by krissch19** [comment]
Call projection to get error-lines for right projection after relax (and figure out issue with multiple windows)

**Comment by krissch19** [comment]
New: When Errorlines are displayed, and nodes are moved, recalculate errorlines.

-> Introduce flags for when errorlines/connectionlines/... are displayed. Watch for those A) on node.nudge in MapDirective(bad way?) or B) in MapController on data update(?)
