### ISSUE TITLE
Adding functionality to disable nodes

### ISSUE THREAD

**Issue by idrissou** [acjim/AcmacsDesktop#73]
Adding a functionality to disable nodes on user request.

**Comment by skjallargrimmur** [comment]
Ill work on that tonight!

**Comment by jidel** [comment]
@idrissou: what exactly do you mean by that? Providing right click menus?? Working on backend integration? Please elaborate.

**Comment by idrissou** [comment]
@skjallargrimmur : don't work on it. I am halfway through it and it is not an urgent task.
@jidel: you click on a node, and then click on a D button and the button becomes grey/white as it will be deselected.

**Comment by idrissou** [comment]
@jidel : exaclty as it is in Derek's desktop application.

**Comment by jidel** [comment]
You mean the node becomes grey? Did you consider the updated toolbar?

**Comment by idrissou** [comment]
@jidel yes, grey, light red or anything we choose.. Light background. You got the idea. .
The functionality is regardless of the toolbar or the button, you call the function, and it will do the job.

**Comment by jidel** [comment]
Ah, okay. So you are not providing a button to do it?

**Comment by idrissou** [comment]
@jidel :) I think you forgot. You told me during our last meeting on Wednsday not to provide the button as you were still delibrating about what is the best option (on the maps's specific window or global like in photoshop or something like that.....)

**Comment by jidel** [comment]
Ah, right. We can talk about it on Wednesday.

**Comment by idrissou** [comment]
https://github.com/acjim/AcmacsDesktop/commit/c764f7d3393b2b0da8d761f184450ec8a2023de5
and https://github.com/acjim/AcmacsDesktop/commit/7471302e56d3623d502f2967e76ffbdfb066c15b

**Comment by idrissou** [comment]
@rohankoid: check out "Disabling Nodes" branch for the Error and get back to me
https://github.com/acjim/AcmacsDesktop/commit/68a9df7899fb23ff4f1d621ae255152b986caaa7

**Comment by rohankoid** [comment]
@idrissou I've made further commit, it was my error, I had a wrong call.

**Comment by rohankoid** [comment]
@idrissou [FileHandlingService.js line no_243]  (https://github.com/acjim/AcmacsDesktop/blob/DisableNodes/src/app/components/filehandling/fileHandlingService.js#L243) wouldn't accept the parameter 'unmovable'. I haven't made changes to it though, it doesn't need the parameter anyway so you can remove it.
