### ISSUE TITLE
Creating a new map from an already existing map

### ISSUE THREAD

**Issue by idrissou** [acjim/AcmacsDesktop#74]
Adding the functionality to create a new map from an already existing one.

**Comment by rohankoid** [comment]
Could you please elaborate a little more @idrissou

**Comment by idrissou** [comment]
Hello man, 
This functionality goes by the user selecting a bunch of nodes as he wishes.
Then clicking on a "create a new map from selected nodes button," 
which will prompt the application to create a new map from the only selected nodes (like the one we had earlier in vis.js)

**Comment by jidel** [comment]
Please refer or close the corresponding issue in your pull request. You can do this by typing
`closes #74`, where the `#74` is the issue number. It makes it easier to talk about pull requests and stuff.
For this, I edited the pull request message.

**Comment by jidel** [comment]
Concernig the code: why are we copying the nodes in d3 and creating a new data structure from that? It would be much easier to do this kind of stuff in the `mapController.js` (and it is actually the right place for that)

**Comment by idrissou** [comment]
@jidel The last time we discussed where code should go, you said: 
live manipulation of data: mapdirective.js
controller: no live manipulation of data functionalities

I am only following the architecture we agreed upon.

**Comment by jidel** [comment]
Manipulation of the DOM, not data

**Comment by idrissou** [comment]
Dom is live data as well.
I won't change the original data as the user may still need the original map.
That is why I am only manipulating the dom data.
Two birds, one stone style.

**Comment by idrissou** [comment]
and for your info, dom means Data object model, so it is data as well...
Please hold your loose horses..

**Comment by jidel** [comment]
@rohankoid: how would the backend handle disabling of nodes?

**Comment by rohankoid** [comment]
You need to supply coordinates of all the points, even those that were not moved. You cannot supply them to relax command, only make_new_projection_and_relax will accept them.

I'll follow up with eugene on this.

**Comment by idrissou** [comment]
https://github.com/acjim/AcmacsDesktop/commit/c764f7d3393b2b0da8d761f184450ec8a2023de5

**Comment by idrissou** [comment]
referenced also by: https://github.com/acjim/AcmacsDesktop/commit/7471302e56d3623d502f2967e76ffbdfb066c15b

**Comment by rohankoid** [comment]
@idrissou you got it other way around. you are supposed to have issue number in commit not the commit number in comment of issue :smile: 

`commit -m 'commit message #74'`

I'm guessing you forgot to add it during commit and added it as comment? 

if this is the case you can do commit --amend (please look at its affect before using of course, note: you can only do it for last/latest commit)

**Comment by idrissou** [comment]
@rohankoid : did you guys change the rule of the game ? 
haha
Since Day 1, I used to do it this way: Check here for an example: https://github.com/acjim/AcmacsDesktop/issues/13

**Comment by rohankoid** [comment]
@idrissou Haha, you had been getting it wrong since day 1 then, github designed the feature to be used other way around, this helps with project management tool (also available on paid version) since one can select an issue and see what are the commits associated with it and what time was spent on it and also helps with other version management tool. Also github beautifully formats the commit messages and shows the association for example see #67 

![screen shot 2015-10-07 at 23 30 43](https://cloud.githubusercontent.com/assets/1008747/10338831/8523e0ae-6d4b-11e5-8f84-089fac9048c1.png)

**Comment by idrissou** [comment]
LOL. Thanks for correcting me man. I stand corrected now ;)

**Comment by jidel** [comment]
Do we want to implement this with the posibility to only selected some nodes and create a map from that? Or just copy the whole map? Copying the whole map would be way easier.

**Comment by idrissou** [comment]
@jidel: Welcome back. I did it the second way (copying the whole map) but got stuck when sending the data to the back-end. Was waiting for Rohan to finish his vacations to ping him on it.

**Comment by idrissou** [comment]
Permanent
