### ISSUE TITLE
Table data not loaded properly

### ISSUE THREAD

**Issue by rohankoid** [acjim/AcmacsDesktop#75]
![screen shot 2015-09-25 at 18 54 50](https://cloud.githubusercontent.com/assets/1008747/10096711/084ef642-63b7-11e5-9c93-65885e19229a.png)

Table data for test data on open not loaded properly.

**Comment by rohankoid** [comment]
@Head this is not fixed.

**Comment by rohankoid** [comment]
ok, issue seems to be with 

```"titers":{
      "number_of_layers":0,
      "titers_list_of_dict":[```

so the property titers_list_of_dict is sometimes written as titers_list_of_list > which is case in most examples it seems, I guess we need to check with Eugene on this @acjim/member

**Comment by jidel** [comment]
Can this be closed? Or do we need to check back with Eugene?

**Comment by rohankoid** [comment]
Emailed eugene with query, waiting for reply.

**Comment by rohankoid** [comment]
Reply from Eugene: 

> The output is correct. Depending on internal structure the titers can be represented as list of lists, i.e. it is dense matrix, or list of dicts (or objects in js notation) and it is sparse matrix. Your program has to support both variants. 

> There could be also layers, i.e. “layers” key in titers object. In that case you may ignore “layers” but you should not allow user to modify titers. Layers means the table is a merge of two or more tables and its titers are compiled from layers. Editing titers of a layered table makes no sense.

**Comment by jidel** [comment]
Information relevant for #81
