### ISSUE TITLE
Handle errors and exceptions

### ISSUE THREAD

**Issue by rohankoid** [acjim/AcmacsDesktop#77]
Handle errors and exceptions properly in promise and file handling along with API.

(stdout errors too)

**Comment by jidel** [comment]
The user should probably not see the detailed output of the backend on an error. A solution is to just say: "Something went wrong" and provide a link to a error file or something similar.

**Comment by rohankoid** [comment]
"Something went wrong" on production environment should be enough. 
I would rather leave the error on dev environment as it is.

**Comment by jidel** [comment]
We could just use the dev_mode flag to check that.

**Comment by rohankoid** [comment]
Yes!

**Comment by jidel** [comment]
Still not perfect..

**Comment by rohankoid** [comment]
Well at least for the ones from api, we could read the output and get 'error' from the output file and return it back. In most cases it would make sense. 

But there are other errors as well, errors and exceptions not related to api. I wanted to  have one point error handling but dont' know how to do it with current architecture.

**Comment by rohankoid** [comment]
From API (Acmacs-web-api) 

![screen shot 2016-01-13 at 09 47 02](https://cloud.githubusercontent.com/assets/1008747/12289236/a53cd1ee-b9da-11e5-83a8-fcda1ee639d6.png)

Error from Acmacs.coreBundle

![screen shot 2016-01-13 at 09 48 41](https://cloud.githubusercontent.com/assets/1008747/12289271/dcd8d814-b9da-11e5-84e2-d0ceff67279a.png)


Where as for system errors like this, i have no idea what would be ideal message. 

![screen shot 2016-01-13 at 09 56 45](https://cloud.githubusercontent.com/assets/1008747/12289754/7d1c9318-b9dd-11e5-9bad-88bd679be587.png)
