### ISSUE TITLE
Add editing functionality of table

### ISSUE THREAD

**Issue by jidel** [acjim/AcmacsDesktop#81]
Add functionality to edit table.

**Comment by rohankoid** [comment]
Sent an email to Eugene for this, awaiting reply

**Comment by rohankoid** [comment]
update_table - Updates table with changes supplied by the user. Supplied data corresponds to the data obtained via get_table command. Antigens/sera can be removed and new antigens/sera can be added. Modifying titers, removing/adding antigens/sera is forbidden if chart has projections and remove_existing_projections optional argument is false (default).
  Mandatory data fields:
    table: dict
    version: int
    info: dict
  Optional data fields:
    remove_existing_projections: bool (default: False)
  Result object:

**Comment by krissch19** [comment]
Also Moore just now mentioned functionality to disable numbers in table, it sort of relates to this issue but also maybe somewhat to #73 ? Not sure, just wanted to write it down.

**Comment by rohankoid** [comment]
@krissch19 if he meant disabling numbers in the table then it would be related to this issue. But I think he said something about disabling nodes which is basically, issue #73

**Comment by rohankoid** [comment]
The api has some error, sent an email to Eugne.

**Comment by rohankoid** [comment]
Issue with call, fixed.

**Comment by rohankoid** [comment]
api updated, new_table usable.

**Comment by rohankoid** [comment]
@jidel @Head I was thinking to may be we should add files for appCtrl, which would be parent controller and would handle scopes for table and map controller. Especially for task like this which would require changes to both the scopes.
