### ISSUE TITLE
Strange cursor behaviour in d3 map

### ISSUE THREAD

**Issue by jidel** [acjim/AcmacsDesktop#83]
If the selection tool is selected, the cursor is changed to `crosshair`. When now clicking in the map and not moving the cursor, the cursor changes to `move`. Once you move the cursor, it switches back to `crosshair`.

It seems as this is somehow caused by the automatically added `.background` div of the d3 map.

**Comment by jidel** [comment]
Seems to be back.

**Comment by idrissou** [comment]
@jidel @rohankoid : I don't see this on my side.
Do you still have this strange behavior?

**Comment by jidel** [comment]
No, seems to be gone again...
