### ISSUE TITLE
Make error message more readable

### ISSUE THREAD

**Issue by jidel** [acjim/AcmacsDesktop#86]
Displaying of an error messages is currently not perfect:
![screen shot 2015-09-28 at 22 11 16 1](https://cloud.githubusercontent.com/assets/6048968/10135027/f7e26b30-662d-11e5-9c5c-fa2067932c16.jpeg)

Points for improvement (from my perspective):
- Move the message to the front
- Show only a generic message with the opportunity to open a log file on the hard drive or sth

**Comment by rohankoid** [comment]
Definitely, it is point for improvement, I have added the comment where I pass the value to this as TODO, I left it so for development purpose for now.

**Comment by rohankoid** [comment]
Still requires proper error handling, related with #77

**Comment by jidel** [comment]
Ah, sorry. Just saw it and this popped into my mind.

**Comment by rohankoid** [comment]
no worries, didn't notice the message was behind any way.
