### ISSUE TITLE
Add functionality: re-optimization of maps

### ISSUE THREAD

**Issue by jidel** [acjim/AcmacsDesktop#88]
After moving points (sera, viruses) around, user should be able to re-opitmize the map, i.e. send it to the backend and get a new map. This should be possible (1) via a menu ("file"? "edit"? I don't know), or (2) via a right-click / context menu (if and when we have a right-click / context menu -- which of course is a separate issue).

- [x] Provide button in GUI
- [x] Provide context menu
- [x] Provide Menu link
- [x] Add api call to the backend

**Comment by rohankoid** [comment]
For this and many other cases where we will be calling api, we need to know the filename of 'outputXXXX.acd1' file. How can this be broadcasted globally @Head ?

**Comment by jidel** [comment]
Is the `outputXXXX.acd1` specific for each ngWindow/map? Or is it only relevant for one specific table?
The question is, if it is dependent on the decision whether to have only one table per app instance or not.

**Comment by rohankoid** [comment]
On how to call api for this: 

<code>
additional_params = {coordinates: list,
    projection: int, map: true};
   api.api.execute(api.get_commands().NEW_PROJECTION, additional_params, output_filename_acd1).then(function(response) {                
        // do the thing
            });
<code>

**Comment by rohankoid** [comment]
@jidel mm regarding your question, no the <code> outputXXXX.acd1 <code> is not specific to each map. Although if you change data in table then <code> outputXXXX_2.acd1 <code> and run it through api then it would be a new one. 
I don't know how we should handle existing maps in this condition though, does this change all opened maps or how, remains open for discussion.

**Comment by Head** [comment]
Regarding the filename (and the data) imho we should put those into a service.
Currently we are passing the data to the winHandler, loosing the control over it in the other parts of the application. Maybe we need to change the map handling to use the data directly from the service, without all those forEach's.

**Comment by jidel** [comment]
A service is a singleton, though. It would be the same service holding all of our map data. I don't see how a separat mapDataService is any different to the winHandler service?
