### ISSUE TITLE
reoptimize

### ISSUE THREAD

**Issue by ProfRon** [acjim/AcmacsDesktop#89]
After moving points (sera, viruses) around, user should be able to re-opitmize the map, i.e. send it to the backend and get a new map.  This should be possible (1) via a menu ("file"? "edit"? I don't know), or (2) via a right-click / context menu (if and when we have a right-click / context menu -- which of course is a separate issue).

**Comment by jidel** [comment]
Valid issue.

**Comment by jidel** [comment]
Duplicate of #88
