### ISSUE TITLE
Saving and opening 

### ISSUE THREAD

**Issue by rohankoid** [acjim/AcmacsDesktop#90]
Add a functionality to save modified maps and re open them.

**Comment by jidel** [comment]
Concerning saving:
We had a discussion of using backend functionality to save our data. However, what happens if we for example move around nodes on a map and don't click `re-optimize`? This change would therefore be lost.

**Comment by idrissou** [comment]
@jidel: after moving the nodes, you mean "you click on optimize", not "don't want to click"
For this case, we will save the current map data by sending it to the backend, get new data of moved points, and re-optimize the last data we got.

**Comment by idrissou** [comment]
We should always do through this when the user clicks on optimization, no matter whether he moves nodes or not.

**Comment by jidel** [comment]
No. I meant it as i wrote it. We change the map, but don't want to reoptimize. How do we save this?

**Comment by idrissou** [comment]
@jidel according to @rohankoid, Eugine implemented this functionality in the backend, and Rohan has already pushed it,  so you just send the new map data to the back-end and get the new table data. save it.

**Comment by rohankoid** [comment]
``api.export`` added and is now usable but it writes files to data/filename.format currently need to work from front-end to save to specified location as export.

We do need to run multiple api calls before export if we want to save current state of the file also don't think it saves all the open maps (need to confirm this). 
Multiple api calls means,
* if table is modified, ``update_table`` needs to be called first.
*if the map has been changed (including-reoptimized) then ``make_new_projection`` needs to be called 

Both of these api's should return new acd1 files which should be used for ``export``

TODO: test ``make_new_projection`` api after modification to core bundle.

**Comment by rohankoid** [comment]
Implemented as export functionality for now.

Issue: https://github.com/nwjs/nw.js/wiki/File-dialogs#filter-file accept doesn't work with nwsaveas

TODO: provide option to export as acd1 and mds (atleast two selectable types).
