### ISSUE TITLE
Display stress values alongside the maps

### ISSUE THREAD

**Issue by jidel** [acjim/AcmacsDesktop#91]
Find a way to display the stress value of the map to the user.

**Comment by rohankoid** [comment]
Note to Rohan (self) TODO: stress is only available on relax of the map, hence add one more call to api to get the stress.

**Comment by jidel** [comment]
Why is stress only available on relax? Shouldn't this be available as soon we get a map?

**Comment by rohankoid** [comment]
I have no idea why, I had thought it would be there on map as well but it's not there it seems. Will need to ask Eugene about it. 

What is stress actually? and how is it calculated? @jidel @krissch19 @idrissou

**Comment by jidel** [comment]
Its a value that indicates how "accurate" a map is. Its kind of a sum of the error lines (at least thats how I imagine it)

**Comment by krissch19** [comment]
guess the connection to errorlines makes sense. The less "stress" the more accurate the map. So when you do optimization and have two results that look similar to the human eye, the stress is an indicator for which map would be the "better one" (the one with least stress) .

**Comment by jidel** [comment]
Not quite: First one after generating map from table:
![screen shot 2015-10-06 at 23 13 58](https://cloud.githubusercontent.com/assets/6048968/10309449/02fc2260-6c80-11e5-9304-8bdfb50114d1.jpeg)
This one after relaxing:
![screen shot 2015-10-06 at 23 14 13](https://cloud.githubusercontent.com/assets/6048968/10309450/033475b6-6c80-11e5-8ce4-25bd04c6a570.jpeg)

**Comment by rohankoid** [comment]
Thanks guys, I did check it and also went through algorithm a little. Johannes is right on it. Relax would basically alter stress so yeah it would make sense to have it with first map. I'll send an email to Eugene right away about it.

**Comment by rohankoid** [comment]
I got in contact with Eugene and briefed about it, he has added stress info on to map data. Need to remake now.

**Comment by idrissou** [comment]
Stress Value Featuring on Top of its respective Map as In Derek's Lisp Version

**Comment by jidel** [comment]
Hi idriss,
I am sorry to say this, but its kind of not the Angular way to do DOM manipulations in a controller. Thats why I suggested doing this in the directive, I think there would be a perfect place for it: https://github.com/acjim/AcmacsDesktop/blob/master/app/components/map/mapDirective.js#L30

You can read a small introduction about AngularJS here:
http://kirkbushell.me/when-to-use-directives-controllers-or-services-in-angular/

If you like, I could show you how to do this so you are good to go for the next time?

**Comment by rohankoid** [comment]
Stress value rounded up to 3 decimal places.
