### ISSUE TITLE
Give user some feedback when loading map

### ISSUE THREAD

**Issue by jidel** [acjim/AcmacsDesktop#94]
When a map is generated, it takes some time (1-2 seconds) until it can be seen. Provide some feedback to the user so that he can be sure everything is working correctly.

One idea: use cursor style `progress` to indicate something is happening in the background (see https://developer.mozilla.org/de/docs/Web/CSS/cursor)

**Comment by rohankoid** [comment]
You need to supply coordinates of all the points, even those that were not moved. You cannot supply them to relax command, only make_new_projection_and_relax will accept them.

I'll follow up with eugene on this.

**Comment by rohankoid** [comment]
Required for #74 #95

**Comment by jidel** [comment]
On opening the app, the loading bar finishes too fast. It finishes before the map window is visible.

**Comment by jidel** [comment]
Seems to be only on startup and loading our development map. Can therefore be ignored.

**Comment by jidel** [comment]
With #117 we open a new app instance for each table/fiel we are opening. A call to the backend is therefore necessary on startup (not only in dev mode).

The loading bar does finishes too fast and the ng-window with the map appears to late.
